BALL_IMAGE = "assets/images/ball.svg"
BULLET_IMAGE = "assets/images/bullet.svg"
CAR_IMAGE = "assets/images/car.svg"
GUN_IMAGE = "assets/images/gun.svg"
GUN_FIRE_IMAGE = "assets/images/gun_fire.svg"
SPACESHIP_IMAGE = "assets/images/spaceship.svg"
TORCH_ON_IMAGE = "assets/images/torch_on.svg"
TORCH_OFF_IMAGE = "assets/images/torch_off.svg"