BULLET_IMAGE = "assets/images/bullet.svg"
CAR_IMAGE = "assets/images/car.svg"
GUN_IMAGE = "assets/images/gun.svg"
SOUND_IMAGE = "assets/images/sound_wave.svg"
SPACESHIP_IMAGE = "assets/images/spaceship.svg"
SPEAKER_IMAGE = "assets/images/torch_on.svg"
TORCH_IMAGE = "assets/images/torch_off.svg"